# https://docs.docker.com/compose/compose-file/

version: "3.2"

services:

    geolocation:
        image: vahpetr/geolocation
        build: geolocation
        ports:
            - "8080:8080"
        env_file:
            - amazon.env
