# https://docs.docker.com/compose/compose-file/

version: "3.2"

services:
    reverseproxy:
        image: vahpetr/reverseproxy
        ports:
            - "80:80"
        networks:
            - geolocation

    geolocation:
        image: vahpetr/geolocation
        # no ports - look only through reverse proxy
        env_file:
            - amazon.env
        networks:
            - geolocation
        deploy:
            replicas: 3
            update_config:
                parallelism: 2
                failure_action: rollback
            placement:
                constraints:
                    - 'node.role == worker'
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s

    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "8001:8080"
        stop_grace_period: 1m30s
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - geolocation
        deploy:
            placement:
                constraints:
                    - 'node.role == manager'

networks:
    geolocation:
