# https://docs.docker.com/compose/compose-file/

version: "3.2"

services:
    geolocation:
        build: geolocation
        ports:
            - "8080:8080"
        env_file:
            - amazon.env
        networks:
            - geolocation

    influxdb:
        image: influxdb
        volumes:
            - influxdb:/var/lib/influxdb
        environment:
            PRE_CREATE_DB: "cadvisor" # not work
        networks:
            - logging

    grafana:
        image: grafana/grafana
        ports:
            - 0.0.0.0:3000:3000
        volumes:
            - grafana:/var/lib/grafana
        networks:
            - logging
        depends_on:
            - influxdb

    cadvisor:
        image: google/cadvisor
        hostname: '{{.Node.ID}}'
        command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        networks:
            - logging
        depends_on:
            - influxdb

volumes:
    influxdb:
        driver: local
    grafana:
        driver: local

networks:
    geolocation:
    logging:
