# https://docs.docker.com/compose/compose-file/

version: "3"

services:

    geolocation:
        image: registry.local:5000/geolocation
        ports:
            - 80:8080
        env_file:
            - amazon.env
        deploy:
            replicas: 3
            update_config:
                parallelism: 2
                delay: 10s
            placement:
                constraints:
                    - node.role == worker
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 60s

    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            mode: global
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 60s
